name: "Feature request"
description: "Suggest an improvement or new capability"
labels: ["type: feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What do you think the framework should do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you’ve tried or considered.
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Links, mockups, related issues, etc.
